-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 18:02:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cursosalumnosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cursosalumnosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cursosalumnosdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `cursosalumnosdb` ;

-- -----------------------------------------------------
-- Table `cursosalumnosdb`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosalumnosdb`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `cursosalumnosdb`.`Cursos` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion` INT NOT NULL,
  `profesor` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(250) NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosalumnosdb`.`Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosalumnosdb`.`Alumnos` ;

CREATE TABLE IF NOT EXISTS `cursosalumnosdb`.`Alumnos` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosalumnosdb`.`Cursos_has_Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosalumnosdb`.`Cursos_has_Alumnos` ;

CREATE TABLE IF NOT EXISTS `cursosalumnosdb`.`Cursos_has_Alumnos` (
  `Cursos_idCurso` INT NOT NULL,
  `Alumnos_idAlumno` INT NOT NULL,
  PRIMARY KEY (`Cursos_idCurso`, `Alumnos_idAlumno`),
  INDEX `fk_Cursos_has_Alumnos_Alumnos1_idx` (`Alumnos_idAlumno` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Alumnos_Cursos_idx` (`Cursos_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Alumnos_Cursos`
    FOREIGN KEY (`Cursos_idCurso`)
    REFERENCES `cursosalumnosdb`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Alumnos_Alumnos1`
    FOREIGN KEY (`Alumnos_idAlumno`)
    REFERENCES `cursosalumnosdb`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
