-- MySQL Script generated by MySQL Workbench
-- Wed Jan  6 12:39:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usuariosdbsec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuariosdbsec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuariosdbsec` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `usuariosdbsec` ;

-- -------------------------------------------------------------------------------------------------
--                           Creacion del usuario de la base de datos                             --
-- -------------------------------------------------------------------------------------------------
grant all privileges on usuariosdbsec.* to 'usuariosdbsec' identified BY '1234567890';
grant all privileges on usuariosdbsec.* to 'usuariosdbsec'@'localhost' identified BY '1234567890';

-- -----------------------------------------------------
-- Table `usuariosdbsec`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuariosdbsec`.`Users` ;

CREATE TABLE IF NOT EXISTS `usuariosdbsec`.`Users` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `enable` TINYINT(1) NOT NULL DEFAULT 1,
  `sub` VARCHAR(255) UNIQUE NULL,-- UNIQUE NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariosdbsec`.`Matriculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuariosdbsec`.`Matriculas` ;

CREATE TABLE IF NOT EXISTS `usuariosdbsec`.`Matriculas` (
  `idMatricula` INT NOT NULL AUTO_INCREMENT,
  `idCurso` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  `Users_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMatricula`, `Users_idUsuario`),
  INDEX `fk_Matriculas_Usuarios_idx` (`Users_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Matriculas_Users`
    FOREIGN KEY (`Users_idUsuario`)
    REFERENCES `usuariosdbsec`.`Users` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariosdbsec`.`Authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuariosdbsec`.`Authorities` ;

CREATE TABLE IF NOT EXISTS `usuariosdbsec`.`Authorities` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariosdbsec`.`Users_has_Authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuariosdbsec`.`Users_has_Authorities` ;

CREATE TABLE IF NOT EXISTS `usuariosdbsec`.`Users_has_Authorities` (
  `Users_idUsuario` INT NOT NULL,
  `Authorities_idRol` INT NOT NULL,
  PRIMARY KEY (`Users_idUsuario`, `Authorities_idRol`),
  INDEX `fk_Users_has_Authorities_Authorities1_idx` (`Authorities_idRol` ASC) VISIBLE,
  INDEX `fk_Users_has_Authorities_Users1_idx` (`Users_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Authorities_Users1`
    FOREIGN KEY (`Users_idUsuario`)
    REFERENCES `usuariosdbsec`.`Users` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Authorities_Authorities1`
    FOREIGN KEY (`Authorities_idRol`)
    REFERENCES `usuariosdbsec`.`Authorities` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
